/*
 * MIS.Back
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ApiProject.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConsultationCreateModel : IEquatable<ConsultationCreateModel>
    {
        /// <summary>
        /// Gets or Sets SpecialityId
        /// </summary>
        [Required]

        [DataMember(Name = "specialityId")]
        public Guid? SpecialityId { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [Required]

        [DataMember(Name = "comment")]
        public InspectionCommentCreateModel Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConsultationCreateModel {\n");
            sb.Append("  SpecialityId: ").Append(SpecialityId).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ConsultationCreateModel)obj);
        }

        /// <summary>
        /// Returns true if ConsultationCreateModel instances are equal
        /// </summary>
        /// <param name="other">Instance of ConsultationCreateModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsultationCreateModel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    SpecialityId == other.SpecialityId ||
                    SpecialityId != null &&
                    SpecialityId.Equals(other.SpecialityId)
                ) &&
                (
                    Comment == other.Comment ||
                    Comment != null &&
                    Comment.Equals(other.Comment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (SpecialityId != null)
                    hashCode = hashCode * 59 + SpecialityId.GetHashCode();
                if (Comment != null)
                    hashCode = hashCode * 59 + Comment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ConsultationCreateModel left, ConsultationCreateModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ConsultationCreateModel left, ConsultationCreateModel right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
