/*
 * MIS.Back
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ApiProject.Models
{

    /// <summary>
    /// Gets or Sets Gender
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum Gender
    {
        /// <summary>
        /// Enum MaleEnum for Male
        /// </summary>
        [EnumMember(Value = "Male")]
        MaleEnum = 0,
        /// <summary>
        /// Enum FemaleEnum for Female
        /// </summary>
        [EnumMember(Value = "Female")]
        FemaleEnum = 1
    }
}
