/*
 * MIS.Back
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ApiProject.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SpecialtiesPagedListModel : IEquatable<SpecialtiesPagedListModel>
    {
        /// <summary>
        /// Gets or Sets Specialties
        /// </summary>

        [DataMember(Name = "specialties")]
        public List<SpecialityModel> Specialties { get; set; }

        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>

        [DataMember(Name = "pagination")]
        public PageInfoModel Pagination { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpecialtiesPagedListModel {\n");
            sb.Append("  Specialties: ").Append(Specialties).Append("\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SpecialtiesPagedListModel)obj);
        }

        /// <summary>
        /// Returns true if SpecialtiesPagedListModel instances are equal
        /// </summary>
        /// <param name="other">Instance of SpecialtiesPagedListModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpecialtiesPagedListModel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Specialties == other.Specialties ||
                    Specialties != null &&
                    Specialties.SequenceEqual(other.Specialties)
                ) &&
                (
                    Pagination == other.Pagination ||
                    Pagination != null &&
                    Pagination.Equals(other.Pagination)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Specialties != null)
                    hashCode = hashCode * 59 + Specialties.GetHashCode();
                if (Pagination != null)
                    hashCode = hashCode * 59 + Pagination.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SpecialtiesPagedListModel left, SpecialtiesPagedListModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpecialtiesPagedListModel left, SpecialtiesPagedListModel right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
