/*
 * MIS.Back
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ApiProject.Data;

namespace ApiProject.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SpecialityAddModel: IEquatable<SpecialityAddModel>
    {
        // /// <summary>
        // /// Gets or Sets CreateTime
        // /// </summary>
        // [Required]

        // [DataMember(Name = "createTime")]
        // public DateTime? CreateTime { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]

        [MinLength(1)]
        [UniqueReflective<ApplicationDbContext, SpecialityModel, string>]
        [DataMember(Name = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpecialityAddModel {\n");
            // sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SpecialityAddModel)obj);
        }

        /// <summary>
        /// Returns true if SpecialityAddModel instances are equal
        /// </summary>
        /// <param name="other">Instance of SpecialityAddModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpecialityAddModel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                // (
                //     CreateTime == other.CreateTime ||
                //     CreateTime != null &&
                //     CreateTime.Equals(other.CreateTime)
                // ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                // if (CreateTime != null)
                //     hashCode = hashCode * 59 + CreateTime.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SpecialityAddModel left, SpecialityAddModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpecialityAddModel left, SpecialityAddModel right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
